Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.network "private_network", ip: "192.168.0.100", :adapter=>2
  config.vm.network "forwarded_port", guest: 22, host: 60000, auto_correct: true, id: "ssh"
  config.vm.network "forwarded_port", guest: 80, host: 60001, auto_correct: true
  config.vm.provision "shell", inline: "sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config"
  config.vm.provision "shell", inline: "systemctl restart ssh"
end
